/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticationLayoutImport } from './routes/authentication/_layout'
import { Route as AuthenticatedLayoutImport } from './routes/authenticated/_layout'
import { Route as AuthenticatedRateAtTeacherImport } from './routes/authenticated/RateAtTeacher'
import { Route as AuthenticationLayoutRegisterImport } from './routes/authentication/_layout/register'
import { Route as AuthenticationLayoutLoginImport } from './routes/authentication/_layout/login'
import { Route as AuthenticatedLayoutTeacherLayoutImport } from './routes/authenticated/_layout/teacher/_layout'
import { Route as AuthenticatedLayoutSchoolLayoutImport } from './routes/authenticated/_layout/school/_layout'
import { Route as AuthenticatedLayoutFeedEditImport } from './routes/authenticated/_layout/feed/edit'
import { Route as AuthenticatedLayoutFeedLayoutImport } from './routes/authenticated/_layout/feed/_layout'
import { Route as AuthenticatedLayoutTeacherLayoutIndexImport } from './routes/authenticated/_layout/teacher/_layout/index'
import { Route as AuthenticatedLayoutSchoolLayoutIndexImport } from './routes/authenticated/_layout/school/_layout/index'
import { Route as AuthenticatedLayoutFeedLayoutIndexImport } from './routes/authenticated/_layout/feed/_layout/index'
import { Route as AuthenticatedLayoutTeacherLayoutPostImport } from './routes/authenticated/_layout/teacher/_layout/post'
import { Route as AuthenticatedLayoutTeacherLayoutTeacherIdImport } from './routes/authenticated/_layout/teacher/_layout/$teacherId'
import { Route as AuthenticatedLayoutSchoolLayoutPostImport } from './routes/authenticated/_layout/school/_layout/post'
import { Route as AuthenticatedLayoutSchoolLayoutSchoolIdImport } from './routes/authenticated/_layout/school/_layout/$schoolId'
import { Route as AuthenticatedLayoutFeedLayoutPostImport } from './routes/authenticated/_layout/feed/_layout/post'

// Create Virtual Routes

const AuthenticationImport = createFileRoute('/authentication')()
const AuthenticatedImport = createFileRoute('/authenticated')()
const AuthenticatedLayoutTeacherImport = createFileRoute(
  '/authenticated/_layout/teacher',
)()
const AuthenticatedLayoutSchoolImport = createFileRoute(
  '/authenticated/_layout/school',
)()
const AuthenticatedLayoutFeedImport = createFileRoute(
  '/authenticated/_layout/feed',
)()

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationLayoutRoute = AuthenticationLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticatedLayoutRoute = AuthenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRateAtTeacherRoute = AuthenticatedRateAtTeacherImport.update(
  {
    id: '/authenticated/RateAtTeacher',
    path: '/authenticated/RateAtTeacher',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthenticatedLayoutTeacherRoute = AuthenticatedLayoutTeacherImport.update(
  {
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any,
)

const AuthenticatedLayoutSchoolRoute = AuthenticatedLayoutSchoolImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const AuthenticatedLayoutFeedRoute = AuthenticatedLayoutFeedImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const AuthenticationLayoutRegisterRoute =
  AuthenticationLayoutRegisterImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticationLayoutRoute,
  } as any)

const AuthenticationLayoutLoginRoute = AuthenticationLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationLayoutRoute,
} as any)

const AuthenticatedLayoutTeacherLayoutRoute =
  AuthenticatedLayoutTeacherLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedLayoutTeacherRoute,
  } as any)

const AuthenticatedLayoutSchoolLayoutRoute =
  AuthenticatedLayoutSchoolLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedLayoutSchoolRoute,
  } as any)

const AuthenticatedLayoutFeedEditRoute =
  AuthenticatedLayoutFeedEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedLayoutFeedRoute,
  } as any)

const AuthenticatedLayoutFeedLayoutRoute =
  AuthenticatedLayoutFeedLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedLayoutFeedRoute,
  } as any)

const AuthenticatedLayoutTeacherLayoutIndexRoute =
  AuthenticatedLayoutTeacherLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutTeacherLayoutRoute,
  } as any)

const AuthenticatedLayoutSchoolLayoutIndexRoute =
  AuthenticatedLayoutSchoolLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutSchoolLayoutRoute,
  } as any)

const AuthenticatedLayoutFeedLayoutIndexRoute =
  AuthenticatedLayoutFeedLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutFeedLayoutRoute,
  } as any)

const AuthenticatedLayoutTeacherLayoutPostRoute =
  AuthenticatedLayoutTeacherLayoutPostImport.update({
    id: '/post',
    path: '/post',
    getParentRoute: () => AuthenticatedLayoutTeacherLayoutRoute,
  } as any)

const AuthenticatedLayoutTeacherLayoutTeacherIdRoute =
  AuthenticatedLayoutTeacherLayoutTeacherIdImport.update({
    id: '/$teacherId',
    path: '/$teacherId',
    getParentRoute: () => AuthenticatedLayoutTeacherLayoutRoute,
  } as any)

const AuthenticatedLayoutSchoolLayoutPostRoute =
  AuthenticatedLayoutSchoolLayoutPostImport.update({
    id: '/post',
    path: '/post',
    getParentRoute: () => AuthenticatedLayoutSchoolLayoutRoute,
  } as any)

const AuthenticatedLayoutSchoolLayoutSchoolIdRoute =
  AuthenticatedLayoutSchoolLayoutSchoolIdImport.update({
    id: '/$schoolId',
    path: '/$schoolId',
    getParentRoute: () => AuthenticatedLayoutSchoolLayoutRoute,
  } as any)

const AuthenticatedLayoutFeedLayoutPostRoute =
  AuthenticatedLayoutFeedLayoutPostImport.update({
    id: '/post',
    path: '/post',
    getParentRoute: () => AuthenticatedLayoutFeedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authenticated/RateAtTeacher': {
      id: '/authenticated/RateAtTeacher'
      path: '/authenticated/RateAtTeacher'
      fullPath: '/authenticated/RateAtTeacher'
      preLoaderRoute: typeof AuthenticatedRateAtTeacherImport
      parentRoute: typeof rootRoute
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/authenticated/_layout': {
      id: '/authenticated/_layout'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedLayoutImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/authentication/_layout': {
      id: '/authentication/_layout'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationLayoutImport
      parentRoute: typeof AuthenticationRoute
    }
    '/authentication/_layout/login': {
      id: '/authentication/_layout/login'
      path: '/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLayoutLoginImport
      parentRoute: typeof AuthenticationLayoutImport
    }
    '/authentication/_layout/register': {
      id: '/authentication/_layout/register'
      path: '/register'
      fullPath: '/authentication/register'
      preLoaderRoute: typeof AuthenticationLayoutRegisterImport
      parentRoute: typeof AuthenticationLayoutImport
    }
    '/authenticated/_layout/feed': {
      id: '/authenticated/_layout/feed'
      path: '/feed'
      fullPath: '/authenticated/feed'
      preLoaderRoute: typeof AuthenticatedLayoutFeedImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/authenticated/_layout/feed/_layout': {
      id: '/authenticated/_layout/feed/_layout'
      path: '/feed'
      fullPath: '/authenticated/feed'
      preLoaderRoute: typeof AuthenticatedLayoutFeedLayoutImport
      parentRoute: typeof AuthenticatedLayoutFeedRoute
    }
    '/authenticated/_layout/feed/edit': {
      id: '/authenticated/_layout/feed/edit'
      path: '/edit'
      fullPath: '/authenticated/feed/edit'
      preLoaderRoute: typeof AuthenticatedLayoutFeedEditImport
      parentRoute: typeof AuthenticatedLayoutFeedImport
    }
    '/authenticated/_layout/school': {
      id: '/authenticated/_layout/school'
      path: '/school'
      fullPath: '/authenticated/school'
      preLoaderRoute: typeof AuthenticatedLayoutSchoolImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/authenticated/_layout/school/_layout': {
      id: '/authenticated/_layout/school/_layout'
      path: '/school'
      fullPath: '/authenticated/school'
      preLoaderRoute: typeof AuthenticatedLayoutSchoolLayoutImport
      parentRoute: typeof AuthenticatedLayoutSchoolRoute
    }
    '/authenticated/_layout/teacher': {
      id: '/authenticated/_layout/teacher'
      path: '/teacher'
      fullPath: '/authenticated/teacher'
      preLoaderRoute: typeof AuthenticatedLayoutTeacherImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/authenticated/_layout/teacher/_layout': {
      id: '/authenticated/_layout/teacher/_layout'
      path: '/teacher'
      fullPath: '/authenticated/teacher'
      preLoaderRoute: typeof AuthenticatedLayoutTeacherLayoutImport
      parentRoute: typeof AuthenticatedLayoutTeacherRoute
    }
    '/authenticated/_layout/feed/_layout/post': {
      id: '/authenticated/_layout/feed/_layout/post'
      path: '/post'
      fullPath: '/authenticated/feed/post'
      preLoaderRoute: typeof AuthenticatedLayoutFeedLayoutPostImport
      parentRoute: typeof AuthenticatedLayoutFeedLayoutImport
    }
    '/authenticated/_layout/school/_layout/$schoolId': {
      id: '/authenticated/_layout/school/_layout/$schoolId'
      path: '/$schoolId'
      fullPath: '/authenticated/school/$schoolId'
      preLoaderRoute: typeof AuthenticatedLayoutSchoolLayoutSchoolIdImport
      parentRoute: typeof AuthenticatedLayoutSchoolLayoutImport
    }
    '/authenticated/_layout/school/_layout/post': {
      id: '/authenticated/_layout/school/_layout/post'
      path: '/post'
      fullPath: '/authenticated/school/post'
      preLoaderRoute: typeof AuthenticatedLayoutSchoolLayoutPostImport
      parentRoute: typeof AuthenticatedLayoutSchoolLayoutImport
    }
    '/authenticated/_layout/teacher/_layout/$teacherId': {
      id: '/authenticated/_layout/teacher/_layout/$teacherId'
      path: '/$teacherId'
      fullPath: '/authenticated/teacher/$teacherId'
      preLoaderRoute: typeof AuthenticatedLayoutTeacherLayoutTeacherIdImport
      parentRoute: typeof AuthenticatedLayoutTeacherLayoutImport
    }
    '/authenticated/_layout/teacher/_layout/post': {
      id: '/authenticated/_layout/teacher/_layout/post'
      path: '/post'
      fullPath: '/authenticated/teacher/post'
      preLoaderRoute: typeof AuthenticatedLayoutTeacherLayoutPostImport
      parentRoute: typeof AuthenticatedLayoutTeacherLayoutImport
    }
    '/authenticated/_layout/feed/_layout/': {
      id: '/authenticated/_layout/feed/_layout/'
      path: '/'
      fullPath: '/authenticated/feed/'
      preLoaderRoute: typeof AuthenticatedLayoutFeedLayoutIndexImport
      parentRoute: typeof AuthenticatedLayoutFeedLayoutImport
    }
    '/authenticated/_layout/school/_layout/': {
      id: '/authenticated/_layout/school/_layout/'
      path: '/'
      fullPath: '/authenticated/school/'
      preLoaderRoute: typeof AuthenticatedLayoutSchoolLayoutIndexImport
      parentRoute: typeof AuthenticatedLayoutSchoolLayoutImport
    }
    '/authenticated/_layout/teacher/_layout/': {
      id: '/authenticated/_layout/teacher/_layout/'
      path: '/'
      fullPath: '/authenticated/teacher/'
      preLoaderRoute: typeof AuthenticatedLayoutTeacherLayoutIndexImport
      parentRoute: typeof AuthenticatedLayoutTeacherLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedLayoutFeedLayoutRouteChildren {
  AuthenticatedLayoutFeedLayoutPostRoute: typeof AuthenticatedLayoutFeedLayoutPostRoute
  AuthenticatedLayoutFeedLayoutIndexRoute: typeof AuthenticatedLayoutFeedLayoutIndexRoute
}

const AuthenticatedLayoutFeedLayoutRouteChildren: AuthenticatedLayoutFeedLayoutRouteChildren =
  {
    AuthenticatedLayoutFeedLayoutPostRoute:
      AuthenticatedLayoutFeedLayoutPostRoute,
    AuthenticatedLayoutFeedLayoutIndexRoute:
      AuthenticatedLayoutFeedLayoutIndexRoute,
  }

const AuthenticatedLayoutFeedLayoutRouteWithChildren =
  AuthenticatedLayoutFeedLayoutRoute._addFileChildren(
    AuthenticatedLayoutFeedLayoutRouteChildren,
  )

interface AuthenticatedLayoutFeedRouteChildren {
  AuthenticatedLayoutFeedLayoutRoute: typeof AuthenticatedLayoutFeedLayoutRouteWithChildren
  AuthenticatedLayoutFeedEditRoute: typeof AuthenticatedLayoutFeedEditRoute
}

const AuthenticatedLayoutFeedRouteChildren: AuthenticatedLayoutFeedRouteChildren =
  {
    AuthenticatedLayoutFeedLayoutRoute:
      AuthenticatedLayoutFeedLayoutRouteWithChildren,
    AuthenticatedLayoutFeedEditRoute: AuthenticatedLayoutFeedEditRoute,
  }

const AuthenticatedLayoutFeedRouteWithChildren =
  AuthenticatedLayoutFeedRoute._addFileChildren(
    AuthenticatedLayoutFeedRouteChildren,
  )

interface AuthenticatedLayoutSchoolLayoutRouteChildren {
  AuthenticatedLayoutSchoolLayoutSchoolIdRoute: typeof AuthenticatedLayoutSchoolLayoutSchoolIdRoute
  AuthenticatedLayoutSchoolLayoutPostRoute: typeof AuthenticatedLayoutSchoolLayoutPostRoute
  AuthenticatedLayoutSchoolLayoutIndexRoute: typeof AuthenticatedLayoutSchoolLayoutIndexRoute
}

const AuthenticatedLayoutSchoolLayoutRouteChildren: AuthenticatedLayoutSchoolLayoutRouteChildren =
  {
    AuthenticatedLayoutSchoolLayoutSchoolIdRoute:
      AuthenticatedLayoutSchoolLayoutSchoolIdRoute,
    AuthenticatedLayoutSchoolLayoutPostRoute:
      AuthenticatedLayoutSchoolLayoutPostRoute,
    AuthenticatedLayoutSchoolLayoutIndexRoute:
      AuthenticatedLayoutSchoolLayoutIndexRoute,
  }

const AuthenticatedLayoutSchoolLayoutRouteWithChildren =
  AuthenticatedLayoutSchoolLayoutRoute._addFileChildren(
    AuthenticatedLayoutSchoolLayoutRouteChildren,
  )

interface AuthenticatedLayoutSchoolRouteChildren {
  AuthenticatedLayoutSchoolLayoutRoute: typeof AuthenticatedLayoutSchoolLayoutRouteWithChildren
}

const AuthenticatedLayoutSchoolRouteChildren: AuthenticatedLayoutSchoolRouteChildren =
  {
    AuthenticatedLayoutSchoolLayoutRoute:
      AuthenticatedLayoutSchoolLayoutRouteWithChildren,
  }

const AuthenticatedLayoutSchoolRouteWithChildren =
  AuthenticatedLayoutSchoolRoute._addFileChildren(
    AuthenticatedLayoutSchoolRouteChildren,
  )

interface AuthenticatedLayoutTeacherLayoutRouteChildren {
  AuthenticatedLayoutTeacherLayoutTeacherIdRoute: typeof AuthenticatedLayoutTeacherLayoutTeacherIdRoute
  AuthenticatedLayoutTeacherLayoutPostRoute: typeof AuthenticatedLayoutTeacherLayoutPostRoute
  AuthenticatedLayoutTeacherLayoutIndexRoute: typeof AuthenticatedLayoutTeacherLayoutIndexRoute
}

const AuthenticatedLayoutTeacherLayoutRouteChildren: AuthenticatedLayoutTeacherLayoutRouteChildren =
  {
    AuthenticatedLayoutTeacherLayoutTeacherIdRoute:
      AuthenticatedLayoutTeacherLayoutTeacherIdRoute,
    AuthenticatedLayoutTeacherLayoutPostRoute:
      AuthenticatedLayoutTeacherLayoutPostRoute,
    AuthenticatedLayoutTeacherLayoutIndexRoute:
      AuthenticatedLayoutTeacherLayoutIndexRoute,
  }

const AuthenticatedLayoutTeacherLayoutRouteWithChildren =
  AuthenticatedLayoutTeacherLayoutRoute._addFileChildren(
    AuthenticatedLayoutTeacherLayoutRouteChildren,
  )

interface AuthenticatedLayoutTeacherRouteChildren {
  AuthenticatedLayoutTeacherLayoutRoute: typeof AuthenticatedLayoutTeacherLayoutRouteWithChildren
}

const AuthenticatedLayoutTeacherRouteChildren: AuthenticatedLayoutTeacherRouteChildren =
  {
    AuthenticatedLayoutTeacherLayoutRoute:
      AuthenticatedLayoutTeacherLayoutRouteWithChildren,
  }

const AuthenticatedLayoutTeacherRouteWithChildren =
  AuthenticatedLayoutTeacherRoute._addFileChildren(
    AuthenticatedLayoutTeacherRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutFeedRoute: typeof AuthenticatedLayoutFeedRouteWithChildren
  AuthenticatedLayoutSchoolRoute: typeof AuthenticatedLayoutSchoolRouteWithChildren
  AuthenticatedLayoutTeacherRoute: typeof AuthenticatedLayoutTeacherRouteWithChildren
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutFeedRoute: AuthenticatedLayoutFeedRouteWithChildren,
  AuthenticatedLayoutSchoolRoute: AuthenticatedLayoutSchoolRouteWithChildren,
  AuthenticatedLayoutTeacherRoute: AuthenticatedLayoutTeacherRouteWithChildren,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationLayoutRouteChildren {
  AuthenticationLayoutLoginRoute: typeof AuthenticationLayoutLoginRoute
  AuthenticationLayoutRegisterRoute: typeof AuthenticationLayoutRegisterRoute
}

const AuthenticationLayoutRouteChildren: AuthenticationLayoutRouteChildren = {
  AuthenticationLayoutLoginRoute: AuthenticationLayoutLoginRoute,
  AuthenticationLayoutRegisterRoute: AuthenticationLayoutRegisterRoute,
}

const AuthenticationLayoutRouteWithChildren =
  AuthenticationLayoutRoute._addFileChildren(AuthenticationLayoutRouteChildren)

interface AuthenticationRouteChildren {
  AuthenticationLayoutRoute: typeof AuthenticationLayoutRouteWithChildren
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLayoutRoute: AuthenticationLayoutRouteWithChildren,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

export interface FileRoutesByFullPath {
  '/authenticated/RateAtTeacher': typeof AuthenticatedRateAtTeacherRoute
  '/authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/authentication': typeof AuthenticationLayoutRouteWithChildren
  '/authentication/login': typeof AuthenticationLayoutLoginRoute
  '/authentication/register': typeof AuthenticationLayoutRegisterRoute
  '/authenticated/feed': typeof AuthenticatedLayoutFeedLayoutRouteWithChildren
  '/authenticated/feed/edit': typeof AuthenticatedLayoutFeedEditRoute
  '/authenticated/school': typeof AuthenticatedLayoutSchoolLayoutRouteWithChildren
  '/authenticated/teacher': typeof AuthenticatedLayoutTeacherLayoutRouteWithChildren
  '/authenticated/feed/post': typeof AuthenticatedLayoutFeedLayoutPostRoute
  '/authenticated/school/$schoolId': typeof AuthenticatedLayoutSchoolLayoutSchoolIdRoute
  '/authenticated/school/post': typeof AuthenticatedLayoutSchoolLayoutPostRoute
  '/authenticated/teacher/$teacherId': typeof AuthenticatedLayoutTeacherLayoutTeacherIdRoute
  '/authenticated/teacher/post': typeof AuthenticatedLayoutTeacherLayoutPostRoute
  '/authenticated/feed/': typeof AuthenticatedLayoutFeedLayoutIndexRoute
  '/authenticated/school/': typeof AuthenticatedLayoutSchoolLayoutIndexRoute
  '/authenticated/teacher/': typeof AuthenticatedLayoutTeacherLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/authenticated/RateAtTeacher': typeof AuthenticatedRateAtTeacherRoute
  '/authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/authentication': typeof AuthenticationLayoutRouteWithChildren
  '/authentication/login': typeof AuthenticationLayoutLoginRoute
  '/authentication/register': typeof AuthenticationLayoutRegisterRoute
  '/authenticated/feed': typeof AuthenticatedLayoutFeedLayoutIndexRoute
  '/authenticated/feed/edit': typeof AuthenticatedLayoutFeedEditRoute
  '/authenticated/school': typeof AuthenticatedLayoutSchoolLayoutIndexRoute
  '/authenticated/teacher': typeof AuthenticatedLayoutTeacherLayoutIndexRoute
  '/authenticated/feed/post': typeof AuthenticatedLayoutFeedLayoutPostRoute
  '/authenticated/school/$schoolId': typeof AuthenticatedLayoutSchoolLayoutSchoolIdRoute
  '/authenticated/school/post': typeof AuthenticatedLayoutSchoolLayoutPostRoute
  '/authenticated/teacher/$teacherId': typeof AuthenticatedLayoutTeacherLayoutTeacherIdRoute
  '/authenticated/teacher/post': typeof AuthenticatedLayoutTeacherLayoutPostRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/authenticated/RateAtTeacher': typeof AuthenticatedRateAtTeacherRoute
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/authentication': typeof AuthenticationRouteWithChildren
  '/authentication/_layout': typeof AuthenticationLayoutRouteWithChildren
  '/authentication/_layout/login': typeof AuthenticationLayoutLoginRoute
  '/authentication/_layout/register': typeof AuthenticationLayoutRegisterRoute
  '/authenticated/_layout/feed': typeof AuthenticatedLayoutFeedRouteWithChildren
  '/authenticated/_layout/feed/_layout': typeof AuthenticatedLayoutFeedLayoutRouteWithChildren
  '/authenticated/_layout/feed/edit': typeof AuthenticatedLayoutFeedEditRoute
  '/authenticated/_layout/school': typeof AuthenticatedLayoutSchoolRouteWithChildren
  '/authenticated/_layout/school/_layout': typeof AuthenticatedLayoutSchoolLayoutRouteWithChildren
  '/authenticated/_layout/teacher': typeof AuthenticatedLayoutTeacherRouteWithChildren
  '/authenticated/_layout/teacher/_layout': typeof AuthenticatedLayoutTeacherLayoutRouteWithChildren
  '/authenticated/_layout/feed/_layout/post': typeof AuthenticatedLayoutFeedLayoutPostRoute
  '/authenticated/_layout/school/_layout/$schoolId': typeof AuthenticatedLayoutSchoolLayoutSchoolIdRoute
  '/authenticated/_layout/school/_layout/post': typeof AuthenticatedLayoutSchoolLayoutPostRoute
  '/authenticated/_layout/teacher/_layout/$teacherId': typeof AuthenticatedLayoutTeacherLayoutTeacherIdRoute
  '/authenticated/_layout/teacher/_layout/post': typeof AuthenticatedLayoutTeacherLayoutPostRoute
  '/authenticated/_layout/feed/_layout/': typeof AuthenticatedLayoutFeedLayoutIndexRoute
  '/authenticated/_layout/school/_layout/': typeof AuthenticatedLayoutSchoolLayoutIndexRoute
  '/authenticated/_layout/teacher/_layout/': typeof AuthenticatedLayoutTeacherLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/authenticated/RateAtTeacher'
    | '/authenticated'
    | '/authentication'
    | '/authentication/login'
    | '/authentication/register'
    | '/authenticated/feed'
    | '/authenticated/feed/edit'
    | '/authenticated/school'
    | '/authenticated/teacher'
    | '/authenticated/feed/post'
    | '/authenticated/school/$schoolId'
    | '/authenticated/school/post'
    | '/authenticated/teacher/$teacherId'
    | '/authenticated/teacher/post'
    | '/authenticated/feed/'
    | '/authenticated/school/'
    | '/authenticated/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/authenticated/RateAtTeacher'
    | '/authenticated'
    | '/authentication'
    | '/authentication/login'
    | '/authentication/register'
    | '/authenticated/feed'
    | '/authenticated/feed/edit'
    | '/authenticated/school'
    | '/authenticated/teacher'
    | '/authenticated/feed/post'
    | '/authenticated/school/$schoolId'
    | '/authenticated/school/post'
    | '/authenticated/teacher/$teacherId'
    | '/authenticated/teacher/post'
  id:
    | '__root__'
    | '/authenticated/RateAtTeacher'
    | '/authenticated'
    | '/authenticated/_layout'
    | '/authentication'
    | '/authentication/_layout'
    | '/authentication/_layout/login'
    | '/authentication/_layout/register'
    | '/authenticated/_layout/feed'
    | '/authenticated/_layout/feed/_layout'
    | '/authenticated/_layout/feed/edit'
    | '/authenticated/_layout/school'
    | '/authenticated/_layout/school/_layout'
    | '/authenticated/_layout/teacher'
    | '/authenticated/_layout/teacher/_layout'
    | '/authenticated/_layout/feed/_layout/post'
    | '/authenticated/_layout/school/_layout/$schoolId'
    | '/authenticated/_layout/school/_layout/post'
    | '/authenticated/_layout/teacher/_layout/$teacherId'
    | '/authenticated/_layout/teacher/_layout/post'
    | '/authenticated/_layout/feed/_layout/'
    | '/authenticated/_layout/school/_layout/'
    | '/authenticated/_layout/teacher/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRateAtTeacherRoute: typeof AuthenticatedRateAtTeacherRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRateAtTeacherRoute: AuthenticatedRateAtTeacherRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/authenticated/RateAtTeacher",
        "/authenticated",
        "/authentication"
      ]
    },
    "/authenticated/RateAtTeacher": {
      "filePath": "authenticated/RateAtTeacher.tsx"
    },
    "/authenticated": {
      "filePath": "authenticated",
      "children": [
        "/authenticated/_layout"
      ]
    },
    "/authenticated/_layout": {
      "filePath": "authenticated/_layout.tsx",
      "parent": "/authenticated",
      "children": [
        "/authenticated/_layout/feed",
        "/authenticated/_layout/school",
        "/authenticated/_layout/teacher"
      ]
    },
    "/authentication": {
      "filePath": "authentication",
      "children": [
        "/authentication/_layout"
      ]
    },
    "/authentication/_layout": {
      "filePath": "authentication/_layout.tsx",
      "parent": "/authentication",
      "children": [
        "/authentication/_layout/login",
        "/authentication/_layout/register"
      ]
    },
    "/authentication/_layout/login": {
      "filePath": "authentication/_layout/login.tsx",
      "parent": "/authentication/_layout"
    },
    "/authentication/_layout/register": {
      "filePath": "authentication/_layout/register.tsx",
      "parent": "/authentication/_layout"
    },
    "/authenticated/_layout/feed": {
      "filePath": "authenticated/_layout/feed",
      "parent": "/authenticated/_layout",
      "children": [
        "/authenticated/_layout/feed/_layout",
        "/authenticated/_layout/feed/edit"
      ]
    },
    "/authenticated/_layout/feed/_layout": {
      "filePath": "authenticated/_layout/feed/_layout.tsx",
      "parent": "/authenticated/_layout/feed",
      "children": [
        "/authenticated/_layout/feed/_layout/post",
        "/authenticated/_layout/feed/_layout/"
      ]
    },
    "/authenticated/_layout/feed/edit": {
      "filePath": "authenticated/_layout/feed/edit.tsx",
      "parent": "/authenticated/_layout/feed"
    },
    "/authenticated/_layout/school": {
      "filePath": "authenticated/_layout/school",
      "parent": "/authenticated/_layout",
      "children": [
        "/authenticated/_layout/school/_layout"
      ]
    },
    "/authenticated/_layout/school/_layout": {
      "filePath": "authenticated/_layout/school/_layout.tsx",
      "parent": "/authenticated/_layout/school",
      "children": [
        "/authenticated/_layout/school/_layout/$schoolId",
        "/authenticated/_layout/school/_layout/post",
        "/authenticated/_layout/school/_layout/"
      ]
    },
    "/authenticated/_layout/teacher": {
      "filePath": "authenticated/_layout/teacher",
      "parent": "/authenticated/_layout",
      "children": [
        "/authenticated/_layout/teacher/_layout"
      ]
    },
    "/authenticated/_layout/teacher/_layout": {
      "filePath": "authenticated/_layout/teacher/_layout.tsx",
      "parent": "/authenticated/_layout/teacher",
      "children": [
        "/authenticated/_layout/teacher/_layout/$teacherId",
        "/authenticated/_layout/teacher/_layout/post",
        "/authenticated/_layout/teacher/_layout/"
      ]
    },
    "/authenticated/_layout/feed/_layout/post": {
      "filePath": "authenticated/_layout/feed/_layout/post.tsx",
      "parent": "/authenticated/_layout/feed/_layout"
    },
    "/authenticated/_layout/school/_layout/$schoolId": {
      "filePath": "authenticated/_layout/school/_layout/$schoolId.tsx",
      "parent": "/authenticated/_layout/school/_layout"
    },
    "/authenticated/_layout/school/_layout/post": {
      "filePath": "authenticated/_layout/school/_layout/post.tsx",
      "parent": "/authenticated/_layout/school/_layout"
    },
    "/authenticated/_layout/teacher/_layout/$teacherId": {
      "filePath": "authenticated/_layout/teacher/_layout/$teacherId.tsx",
      "parent": "/authenticated/_layout/teacher/_layout"
    },
    "/authenticated/_layout/teacher/_layout/post": {
      "filePath": "authenticated/_layout/teacher/_layout/post.tsx",
      "parent": "/authenticated/_layout/teacher/_layout"
    },
    "/authenticated/_layout/feed/_layout/": {
      "filePath": "authenticated/_layout/feed/_layout/index.tsx",
      "parent": "/authenticated/_layout/feed/_layout"
    },
    "/authenticated/_layout/school/_layout/": {
      "filePath": "authenticated/_layout/school/_layout/index.tsx",
      "parent": "/authenticated/_layout/school/_layout"
    },
    "/authenticated/_layout/teacher/_layout/": {
      "filePath": "authenticated/_layout/teacher/_layout/index.tsx",
      "parent": "/authenticated/_layout/teacher/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
